### PR TITLE
++ tests/generate scripts

### PR DESCRIPTION
**Pull request by radonnachie**

### CODE REVIEW

**Comment by radonnachie** [comment]
I'm currently faced with a FloatingPoint exception when I run on the generated inputs (see `tests/test.sh`). I suspect that this is due to the BF-Recipe I've generated, which populates many fields with random floats.

```
CBF: Using host arrays allocated in pinned memory
starting thread 'hpguppi_rawfile_input_thread' with databufs 0 and 1
Thu May 19 21:17:39 2022 : Info (hashpipe_thread_run): Masking hpguppi_rawfile_input_thread:
RAW INPUT: Got current RAW file: /home/cosmic/dev/hpguppi_proc/tests/golden_input.0000.raw
RAW INPUT: The last position of . is 48 
RAW INPUT: Base filename from command: /home/cosmic/dev/hpguppi_proc/tests/golden_input 
RAW INPUT: The last position of / is 35 
RAW INPUT: File name with no path: golden_input 
RAW INPUT: Opening first raw file '/home/cosmic/dev/hpguppi_proc/tests/golden_input.0000.raw'
RAW INPUT: Current pktidx = 0 and next pktidx = 0 
RAW INPUT: Number of bytes read in read(): 134217728 
RAW INPUT: Current pktidx = 0 and next pktidx = 0 
CBF: pktidx = 0, pktstart = 0, and pktstop = 27459584
CBF: schan = 0 
CBF: RAW file base filename:          golden_input 
CBF: Previous RAW file base filename: golden_input 
../init/readraw_init.sh: line 152: 72702 Floating point exception(core dumped) $hashpipe_cmd_prefix -p ${hpguppi_plugin:-hpguppi_proc} $net_thread $out_thread -o INPUTDIR=${inputdir} -o BFRDIR=${bfrdir} -o OUTDIR=${outdir} -o RAWFILE=${rawfile}
```

**Comment by lacker** [comment]
Nice, seems like pretty good progress. If there's anything else you did to get the C environment set up, do you mind adding notes on it to the README in this repo?

**Comment by lacker** [comment]
Is it possible to run hashpipe via gdb? It seems like it would be handy to see what line of code the floating point exception is coming from....

**Comment by radonnachie** [comment]
I cloned and `make`d both [pyslalib](https://github.com/scottransom/pyslalib) and [rawspec](https://github.com/UCBerkeleySETI/rawspec), and pointed to them in `./configure --with-libsla=... --with-rawspec=...`.
Because I have to `sudo` run hashpipe, I export my user's `~` path to `HASHPIPE_KEYFILE_PATH` so that the instance determines the same IPC key as any related functions I run. That was a tricky point to figure out, but I don't think that it is pertinent to the `./readraw_init.sh` case. I'm happy to help with any particular hurdles you're facing. Offline or in a separate issue.

Rather embarrassingly I'm not very well acquainted with gdb. Which may be why my attempt failed:
```
sudo HASHPIPE_KEYFILE=/home/cosmic LD_LIBRARY_PATH=/home/cosmic/src/rawspec gdb --args /home/cosmic/dev/hashpipe/src/hashpipe -I 3 -p ../src/.libs/hpguppi_proc.so hpguppi_rawfile_input_thread hpguppi_coherent_bf_thread -o INPUTDIR=/home/cosmic/dev/hpguppi_proc/tests -o BFRDIR=./bf_recipe.h5 -o OUTDIR=./output -o RAWFILE=golden_input.0000.raw
GNU gdb (Ubuntu 9.2-0ubuntu1~20.04.1) 9.2
...
"/home/cosmic/dev/hashpipe/src/hashpipe": not in executable format: file format not recognized
(gdb)
```

**Comment by texadactyl** [comment]
@radonnachie 
I do this when debugging rawspec:

```
gdb --args '/home/texadactyl/rawspec/rawspec' '--fbh5' '--debug'  '-f' '8192' '-t' '2' '-g' '2' '-i' '1.0'  'guppi_59229_47368_006379_40blocks' 
```
When gdb pauses, type: run

Can you do something similar with hashpipe?
Missing quotes?

**Comment by lacker** [comment]
I think to run gdb usefully, you typically need to compile with the `-g` flag to include debug info. I'm not really sure how it will work with the whole hashpipe-including-the-other-so's, maybe you only need to compile the hpguppi_proc stuff with `-g` to get useful output?

**Comment by radonnachie** [comment]
Both the hashpipe and hpguppi_proc repos have the `-ggdb` flag.
The quotes did nothing.

**Comment by radonnachie** [comment]
Also, the executable flag is set across the board for `-rwxrwxr-x 1 radonn swdev 6.2K Feb 10 16:25 /home/cosmic/dev/hashpipe/src/hashpipe`

**Comment by texadactyl** [comment]
Key message:  "file format not recognized".  Not an executable binary?

**Comment by lacker** [comment]
Can you paste the full output of your failed gdb run?

**Comment by radonnachie** [comment]
Certainly is executable
```
$ /home/cosmic/dev/hashpipe/src/hashpipe
No threads specified!
Known input-only threads:
Known input/output threads:
Known output-only threads:
  null_output_thread
Known utility threads:
```

Here is the full gdb output:
```
$ sudo HASHPIPE_KEYFILE=/home/cosmic LD_LIBRARY_PATH=/home/cosmic/src/rawspec gdb --args '/home/cosmic/dev/hashpipe/src/hashpipe' '-I' '3' '-p' '../src/.libs/hpguppi_proc.so' 'hpguppi_rawfile_input_thread' 'hpguppi_coherent_bf_thread' '-o' 'INPUTDIR=/home/cosmic/dev/hpguppi_proc/tests' '-o' 'BFRDIR=./bf_recipe.h5' '-o' 'OUTDIR=./output' '-o' 'RAWFILE=golden_input.0000.raw'
[sudo] password for radonn: 
GNU gdb (Ubuntu 9.2-0ubuntu1~20.04.1) 9.2
Copyright (C) 2020 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
"/home/cosmic/dev/hashpipe/src/hashpipe": not in executable format: file format not recognized
(gdb) quit
```

**Comment by texadactyl** [comment]
Is /home/cosmic/dev/hashpipe/src/hashpipe a binary or a bash script?

**Comment by radonnachie** [comment]
It's a bash script... I just opened it 👎

**Comment by texadactyl** [comment]
cannot run gdb on a bash script!!!

**Comment by texadactyl** [comment]
Do gdb inside the script

**Comment by texadactyl** [comment]
or run the binary on command line

**Comment by texadactyl** [comment]
gdb --args binary .....

**Comment by radonnachie** [comment]
It's a libtool generated bash. [This](https://www.gnu.org/software/libtool/manual/html_node/Debugging-executables.html) suggests `libtool --mode=execute gdb...`

**Comment by radonnachie** [comment]
Found that the `hashpipe/src/.libs/hashpipe` executable was acceptable, and that that directory needed to be added to `LD_LIBRARY_PATH`. Result is that gdb highlights:
```
CBF: RAW file base filename:          golden_input 
CBF: Previous RAW file base filename: golden_input 

Thread 2 "hashpipe" received signal SIGFPE, Arithmetic exception.
[Switching to Thread 0x7fffde0e7700 (LWP 76074)]
0x00007ffff7c2fde0 in run (args=<optimized out>) at hpguppi_coherent_bf_thread.c:374
warning: Source file is more recent than executable.
374           // Calculate coarse channel center frequencies depending on the mode and center frequency that spans the RAW file
```

While 375 seems more likely to be the issue `n_chan_per_node = (int)obsnchan/nants; //((int)fenchan)/n_nodes;`. So I'll look to fix the `nants` source! Thanks for the company!

----------------------
Final command run, no quotes needed:
`sudo HASHPIPE_KEYFILE=/home/cosmic LD_LIBRARY_PATH=/home/cosmic/src/rawspec:/home/cosmic/dev/hashpipe/src/.libs gdb --args /home/cosmic/dev/hashpipe/src/.libs/hashpipe -I 3 -p ../src/.libs/hpguppi_proc.so hpguppi_rawfile_input_thread hpguppi_coherent_bf_thread -o INPUTDIR=/home/cosmic/dev/hpguppi_proc/tests -o BFRDIR=./bf_recipe.h5 -o OUTDIR=./output -o RAWFILE=golden_input.0000.raw`

**Comment by lacker** [comment]
By the way it might be a good idea when generating test data to skip some blocks - there's a decent amount of code in hpguppi_proc designed to handle missing blocks, and having that happen occasionally in the test data would ensure you're testing that code path as well

**Comment by radonnachie** [comment]
Some things to note:

- The test inputs must have dimensions that match those statically defined in `https://github.com/UCBerkeleySETI/hpguppi_proc/blob/mark_r/coherent_beamformer/src/coherent_beamformer_char_in.h`. Currently that means there are 64 beams formed, which perhaps is overkill for the golden i/o set.
- The tests aren't neatly set up so that one can define which directory to run in (to integrate NVMe performance boosts etc).
- I haven't committed the outputs as the raw_input thread won't stop reading in the same blocks. So I'll tackle that first.

**Pull request merged**
